### ISSUE TITLE
Harden your GitHub account

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-BlackSou#1]
Enable 2FA:
* [x] proceed at https://github.com/settings/security
* [x] I recommend using the following OTP code generator: https://play.google.com/store/apps/details?id=org.liberty.android.freeotpplus&hl=en_US

**Comment by BlackSou** [comment]
I recommend using the following OTP code generator: https://play.google.com/store/apps/details?id=org.liberty.android.freeotpplus&hl=en_US

> В мене iPhone такого додатку немає в AppStore

**Comment by webknjaz** [comment]
There's an app called FreeOTP then.

**Comment by webknjaz** [comment]
Why did you reopen it? I see that it's solved.
