### ISSUE TITLE
Install and configure an operating system of the GNU/Linux family

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-BlackSou#2]
* [x] Install [XUbuntu](https://xubuntu.org/)
* [x] Learn about APT. [Here](https://help.ubuntu.com/lts/serverguide/apt.html.en) and [there](https://help.ubuntu.com/community/AptGet/Howto)
* [x] Install [Kitty terminal emulator](https://sw.kovidgoyal.net/kitty/binary.html)
* [x] [Install Google Chrome](https://www.linuxbabe.com/ubuntu/install-google-chrome-ubuntu-18-04-lts) but scroll to the section `"Install Google Chrome on Ubuntu 18.04 LTS from the Command Line"` and use it. No GUI-based install, please
* [x] Install [Git from PPA](https://git-scm.com/download/linux)
* [x] Install VS Code using [this instruction](https://code.visualstudio.com/docs/setup/linux#_installation), **but** without downloading `*.deb` file so find the line `"The repository and key can also be installed manually with the following script:"` and go from there

**Comment by BlackSou** [comment]
Install XUbuntu 
> I installed Ubuntu

**Comment by BlackSou** [comment]
Learn about APT. Here and there

>Just I need to read about APT?

**Comment by webknjaz** [comment]
@BlackSou I just want you to know basics of how to use it for starters.

P.S. When you use `>` it'll render a blockquote. Using it for the reply is incorrect.

**Comment by BlackSou** [comment]
@webknjaz  Ok, i understand you.

**Comment by BlackSou** [comment]
@webknjaz Why without downloading *.deb?

**Comment by webknjaz** [comment]
@BlackSou Because I want you to learn how to work with the terminal better. You can start @ 
`The repository and key can also be installed manually with the following script:` phrase under `Debian and Ubuntu based distributions`, a few paragraphs below.
You'll need this skill once you face SSH on a real job and will log in to servers/VMs without any GUI on board.

**Comment by BlackSou** [comment]
@webknjaz okay))

**Comment by webknjaz** [comment]
Why do you reopen solved issues?
