### ISSUE TITLE
Learn Git

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-BlackSou#4]
![](https://cdnb.artstation.com/p/assets/images/images/019/282/033/large/sanjay-singh-samurai05.jpg?1562786772)

Please read&learn the following:

* [ ] [ProGit 2](https://git-scm.com/book/en/v2) [:ukraine:](https://git-scm.com/book/uk/v2)
* [x] [Try Git](https://try.github.io/)
* [x] [Try Git Branching](http://learngitbranching.js.org/)
* [x] [Interactive diagram/cheatsheet about git](http://ndpsoftware.com/git-cheatsheet.html)
* [x] [You're using git wrong](https://web.archive.org/web/20181029051129/https://dpc.pw/blog/2017/08/youre-using-git-wrong/)
* [ ] [Learn git concepts, not commands](https://dev.to/unseenwizzard/learn-git-concepts-not-commands-4gjc)

Extras:
* [x] [A useful template for commit messages](http://codeinthehole.com/tips/a-useful-template-for-commit-messages/)
* [x] [Understanding the GitHub Flow](https://guides.github.com/introduction/flow/)
* [x] [Closing issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/)

**Comment by BlackSou** [comment]
@webknjaz  I need to read whole the book( https://git-scm.com/book/en/v2 )  ?

**Comment by webknjaz** [comment]
First, read at least the first 3 chapters and then read the rest while you're working on other things in parallel (asynchronously, when you have time).

**Comment by BlackSou** [comment]
@webknjaz Okay)

**Comment by BlackSou** [comment]
closes #4

**Comment by webknjaz** [comment]
> closes #4

Such comments only work when you refer issues from PRs and commits once they get merged.
